### PR TITLE
Add prefixes for values on x and y axes

### PR DESCRIPTION
**Pull request by daveslutzkin**
I wanted to be able to add dollar signs to the values on the axes of my charts, so I added a general param for a string prefix to all values on the axes.

### CODE REVIEW

**Comment by daveslutzkin** [comment]
I though better of "prefixes" seeing as d3-format can handle all of this better than that, so now it's possible to pass format strings through.

**Comment by jwilber** [comment]
Great idea, thanks for the work!
Can you add `d3-format` to the `package.json` dependencies?

**Comment by daveslutzkin** [comment]
@jwilber done

**Comment by jwilber** [comment]
Great, thank you! :)

**Comment by jwilber** [comment]
I'm going to add some more changes before pushing out a new version, but this will be added in that new version (should be tonight or later this week).

**Pull request merged**
